title: Thang's Notes
description: You cannot teach a man anything, you can only help him find it within himself. —– Galileo Galilei (1564–1642)

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://tinyurl.com/yflyokje

theme: null

# debug:
#   compress: true
#   dist: false
#   shortcodes: true

readme_index:
  with_frontmatter: true

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions

# Exclude these files from your production _site
exclude:
  - Makefile
  - CNAME
  - LICENSE
  - update.sh
  - Gemfile
  - Gemfile.lock
  - requirements.txt
  - node_modules
  - package.json
  - package-lock.json
  - webpack.config.js
  - jekyll-rtd-theme.gemspec


# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email:
  facebook: thangckt111
  flickr:
  github: 
  instagram:
  linkedin:
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter: 
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/

# tracker
  gtag: UA-174315734-1
  adsense: <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-1573099456298501"
     crossorigin="anonymous"></script>
