theme: null

debug:
  dist: true
  compress: true
  shortcodes: true

sass:
  style: compressed

readme_index:
  with_frontmatter: true

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions

exclude:
  - Makefile
  - CNAME
  - LICENSE
  - update.sh
  - Gemfile
  - Gemfile.lock
  - requirements.txt
  - node_modules
  - package.json
  - package-lock.json
  - webpack.config.js
  - jekyll-rtd-theme.gemspec
